#
# Code Climate Quality configuration file
#
# Helps keep code and documentation clean.
#
# Advanced configuration reference:
#   https://docs.codeclimate.com/docs/advanced-configuration

#

version: 2

# Enable community plugins
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
