#
# Code Climate Quality configuration file
#
# Helps keep code and documentation clean.
#
# @link https://docs.codeclimate.com/
#

version: 2

# Enable community plugins
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
