#!/bin/bash
#
# Docker build hook override
#
# See https://docs.docker.com/docker-cloud/builds/advanced/
#

# Optimize shell for safety.
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# Define variables.
{ echo "Determine which Dockerfile to use:"; } 2> /dev/null
DOCKERFILE="Dockerfile"
if [[ "$DOCKER_TAG" =~ ^(amd64|i386)$ ]]; then
    DOCKERFILE="Dockerfile-debian.Dockerfile"
fi

# Build Docker image.
{ echo "Build Docker image:"; } 2> /dev/null
docker build \
	--build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
	--build-arg VCS_REF="$(git rev-parse --short HEAD)" \
	--tag "$IMAGE_NAME" \
	--file "$DOCKERFILE" \
	.

# Exit with the status of the last command
exit $?
