#!/bin/bash
#
# Docker post_checkout hook override
#
# See https://docs.docker.com/docker-cloud/builds/advanced/
#

# Optimize shell for safety.
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# Replace Dockerfile default base image with tag-related one.
{ echo "Define base image as balenalib/${DOCKER_TAG} in Dockerfile:"; } 2> /dev/null
if [[ "$DOCKER_TAG" =~ ^(aarch64|armv7hf)$ ]]; then
    sed -i "s|FROM balenalib/rpi-|FROM balenalib/${DOCKER_TAG}-|" Dockerfile
elif [[ "$DOCKER_TAG" =~ ^(i386)$ ]]; then
    sed -i "s|FROM balenalib/amd64-|FROM balenalib/${DOCKER_TAG}-|" Dockerfile-debian.Dockerfile
    sed -i "s|ENV FLICLIB_ARCH x86_64|ENV FLICLIB_ARCH ${DOCKER_TAG}|" Dockerfile-debian.Dockerfile
fi

# Exit with the status of the last command
exit $?
